### ISSUE TITLE
Does not work if Cloudflare token starts with "-" 

### ISSUE THREAD

**Issue by ahmetb** [NathanVaughn/actions-cloudflare-purge#39]
I'm customizing env vars as follows:

```

      - name: Cloudflare Cache Purge
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
            cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}

```

My token contains a "-" as its first character and in the GitHub Action output I'm seeing that python tries to interpret the value as an `-option`:

```
Run nathanvaughn/actions-cloudflare-purge@master
  with:
    cf_zone: ***
    cf_auth: ***
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/blog/blog/gha-creds-851f5[2](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:2)[3](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:3)[4](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:4)[5](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:5)41a0be5.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/blog/blog/gha-creds-851f5234541a0be5.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/blog/blog/gha-creds-851f5234541a0be5.json
    CLOUDSDK_CORE_PROJECT: ahmetb-blog
    CLOUDSDK_PROJECT: ahmetb-blog
    GCLOUD_PROJECT: ahmetb-blog
    GCP_PROJECT: ahmetb-blog
    GOOGLE_CLOUD_PROJECT: ahmetb-blog
/usr/bin/docker run --name d20985be[6](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:6)9494c5db[7](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:7)5c30e0fdd57[8](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:8)71_d[9](https://github.com/ahmetb/blog/actions/runs/3797304137/jobs/6458111224#step:8:9)f750 --label 290506 --workdir /github/workspace --rm -e "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE" -e "GOOGLE_APPLICATION_CREDENTIALS" -e "GOOGLE_GHA_CREDS_PATH" -e "CLOUDSDK_CORE_PROJECT" -e "CLOUDSDK_PROJECT" -e "GCLOUD_PROJECT" -e "GCP_PROJECT" -e "GOOGLE_CLOUD_PROJECT" -e "INPUT_CF_ZONE" -e "INPUT_CF_AUTH" -e "INPUT_URLS" -e "INPUT_FILES" -e "INPUT_TAGS" -e "INPUT_HOSTS" -e "INPUT_PREFIXES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/blog/blog":"/github/workspace" 290506:d20985be69494c5db75c30e0fdd57871  "--cf-zone" "***" "--cf-auth" "***" "--urls" "" "--files" "" "--tags" "" "--hosts" "" "--prefixes" ""
usage: main.py [-h] [--cf-zone [CF_ZONE]] [--cf-auth [CF_AUTH]]
               [--urls [URLS ...]] [--files [FILES ...]] [--tags [TAGS ...]]
               [--hosts [HOSTS ...]] [--prefixes [PREFIXES ...]]
main.py: error: unrecognized arguments: ***
```
